class ThreatReports:
    def __init__(self):
        pass

    @classmethod
    def threatgroup_pass(cls):
        return {
            "fileName": "itg10.md",
            "content-type": "X-IBM/Report-threatgroup",
            "created": "2019-06-04T18:00:13Z",
            "published": "2019-08-17T23:28:27Z",
            "title": "ITG10 Analysis Report",
            "summary": "ITG10, also known as APT37/Reaper, Scarcruft, Group123, Red Eyes, Geumseong121, is a threat group likely backed by the Democratic People’s Republic of Korea (DPRK or North Korea) government and has been active since at least 2012 .  First reported in 2016 , ITG10 primarily focuses on gathering information related to political, military, and to a lesser degree, financial data, that is of strategic interest to the DPRK government.  ITG10 has demonstrated clear technical sophistication deploying zero-days , custom malware, and the use of mobile platforms to collect on and exploit targets. Geographically, while ITG10 has focused much of its activities against the Republic of Korea (also known as South Korea), the group has also targeted various other nations, probably to support DPRK government’s foreign policy objectives.  IBM X-Force IRIS assess with high confidence that individuals and organizations holding strategic political or military information in connection with the Korean peninsula will continue to face an elevated risk from ITG10.",
            "entitlement": "premium",
            "indicators": [],
            "primary_tag": "thr.itg10",
            "tags": [
                "thr.itg10",
                "bhv.role.installer",
                "bhv.capa.anti.tool",
                "bhv.aka.vt.tag.assembly",
                "bhv.capa.os.reboot",
                "bhv.capa.file.read",
                "bhv.role.downloader",
                "bhv.aka.cisco.op.evilnewyear2018",
                "bhv.capa.av.symantec",
                "bhv.aka.vt.tag.corrupt",
                "bhv.capa.encode.base64",
                "bhv.capa.datamine.screen",
                "bhv.meth.fileops.macros",
                "bhv.capa.datamine.clipboard",
                "bhv.aka.vt.tag.zip",
                "bhv.capa.comm.http",
                "bhv.aka.estsecurity.op.rocketman",
                "omit.benign",
                "bhv.aka.vt.tag.cve_2018_0802",
                "bhv.published.paloalto",
                "bhv.aka.vt.tag.cve_2016_7262",
                "bhv.capa.anti.debug",
                "bhv.aka.cisco.op.evilnewyear",
                "mal.exploit.cve.2018.4878",
                "bhv.meth.coopt.decoy",
                "bhv.aka.vt.tag.hwp",
                "bhv.avail.nonpublic",
                "bhv.capa.ps.create",
                "bhv.aka.vt.tag.doc",
                "bhv.meth.c2",
                "bhv.capa.file.mod",
                "bhv.aka.vt.tag.cve_2017_11882",
                "mal.gen",
                "bhv.aka.securelist.op.daybreak",
                "bhv.aka.vt.tag.flash",
                "bhv.meth.fileops.pack.upx",
                "bhv.meth.exfil",
                "bhv.aka.vt.tag.html",
                "bhv.meth.netops.web.dropbox",
                "bhv.aka.paloalto.thr.reaper",
                "bhv.aka.vt.tag.loadbytes",
                "bhv.role.exploit",
                "bhv.meth.fileops.masq",
                "bhv.aka.vt.tag.cve_2015_2545",
                "bhv.meth.fileops.macro",
                "bhv.meth.hostops.user.perm.mod",
                "bhv.meth.netops.encrypt.aes",
                "bhv.aka.vt.tag.signed",
                "bhv.aka.vt.tag.cve_2017_8291",
                "bhv.meth.netops.icmp.ping",
                "bhv.aka.vt.tag.pedll",
                "bhv.aka.vt.tag.rtf",
                "bhv.capa.dir",
                "bhv.capa.file.download",
                "bhv.aka.vt.tag.contains_elf",
                "bhv.capa.ps",
                "bhv.role.backdoor",
                "bhv.aka.vt.tag.php",
                "bhv.cpa.c2",
                "bhv.published.carbonblack",
                "bhv.aka.vt.tag.attachment",
                "bhv.meth.phish.payload.attach",
                "bhv.aka.carbonblack.mal.dogcall",
                "bhv.aka.cisco.mal.rokrat",
                "bhv.meth.fileops.obf.encode.xor",
                "bhv.meth.codelang.cpp",
                "bhv.capa.exec",
                "bhv.aka.vt.tag.cve_2018_4878",
                "bhv.capa.net.proxy.mod",
                "bhv.aka.vt.tag.via_tor",
                "bhv.capa.comm.udp",
                "bhv.capa.svc.mod",
                "trend.lifecycle.intrecon",
                "bhv.published.estsecurity",
                "trend.lifecycle.datatheft",
                "bhv.aka.securelist.thr.scarcruft",
                "bhv.capa.crypt.aes",
                "bhv.capa.os.shutdown",
                "bhv.capa.file.upload",
                "bhv.capa.sleep",
                "bhv.capa.ps.kill",
                "bhv.meth.phish.payload",
                "bhv.aka.vt.tag.nsrl",
                "bhv.aka.vt.tag.text",
                "bhv.aka.vt.tag.peexe",
                "bhv.capa.exec.shell",
                "bhv.aka.carbonblack.mal.rokrat",
                "bhv.capa.regkey.mod",
                "bhv.capa.anti.vm",
                "bhv.meth.hostops.user.del",
                "bhv.role.dropper",
                "bhv.capa.perisst.regkey",
                "bhv.aka.vt.tag.xlsx",
                "bhv.aka.vt.tag.overlay",
                "bhv.capa.file.downlaod",
                "bhv.capa.datamine.audio",
                "bhv.role.archive",
                "bhv.meth.netops.web.redirect",
                "bhv.aka.vt.tag.cve_2017_8759",
                "bhv.aka.vt.tag.ole_embedded",
                "bhv.aka.vt.tag.android",
                "bhv.meth.webcomp.payload",
                "bhv.aka.vt.tag.upx",
                "bhv.capa.datamine.webcam",
                "bhv.aka.vt.tag.exploit",
                "bhv.aka.estsecurity.op.goldenbird",
                "bhv.capa.file.exec",
                "bhv.capa.svc.create",
                "bhv.aka.cisco.thr.group123",
                "bhv.capa.file.del",
                "bhv.capa.datamine.keylog",
                "bhv.aka.estsecurity.thr.geumseong121group",
                "bhv.capa.encode.xor",
                "bhv.published.kaspersky",
                "bhv.meth.filelops.macro",
                "bhv.capa.persist.regkey",
                "bhv.capa.file.create",
                "bhv.capa.c2",
                "bhv.capa.datamine.sysinfo",
                "bhv.aka.vt.tag.mz",
                "bhv.published.cisco",
                "bhv.aka.vt.tag.cve_2013_0808",
                "bhv.capa.svc",
                "bhv.aka.estsecurity.op.blackbanner",
                "bhv.capa.datamine.mail",
                "bhv.aka.vt.tag.capabilities",
                "bhv.aka.vt.tag.apk",
                "mal.karae",
                "bhv.role.keylogger",
                "bhv.capa"
            ],
            "content": "# ITG10 Analysis Report\n\n## Summary\nITG10, also known as APT37/Reaper, Scarcruft, Group123, Red Eyes"
        }

    @classmethod
    def hive_pass(cls):
        return {
            "fileName": "hive0013.md",
            "content-type": "X-IBM/Report-threatgroup",
            "created": "2019-08-17T23:28:25Z",
            "published": "2019-08-17T23:28:25Z",
            "title": "Hive0013 Analysis Report",
            "summary": "Since at least 2014, likely Vietnam-sponsored Advanced Persistent Threat (APT) group OceanLotus, tracked by IBM as Hive0013 and also known as APT32, has targeted Southeast Asian organizations, according to multiple security research firms.  OceanLotus has targeted various sectors, including manufacturing, media, network security, consumer products, banking, automotive, and hospitality, making them a cross-industry threat actor group.  In addition to targeting organizations within Southeast Asia, OceanLotus actors have been observed attempting to infiltrate international entities seeking to enter Southeast Asia or with significant Southeast Asia presence, such as a European manufacturing firm looking to start a major project in Vietnam.  The purpose of this targeting is unknown, but could involve intellectual property theft. Beyond commercial targeting, OceanLotus has also been seen engaging in espionage operations in apparent congruity with Vietnamese government national interests, including targeting of human rights organizations and Vietnamese citizens abroad.    \nOceanLotus traditionally uses phishing emails with malicious attachments to infect victims. The emails sent show multilingual capability and careful tailoring of email content to the intended target.  The malicious attachments have been both decoy documents as well as fake installers; both types leverage sophisticated obfuscation techniques to evade detection when executed, such as masquerading as a Windows hotfix.    Additionally, OceanLotus has been observed using watering holes to infect victims.  OceanLotus has continued to evolve its malware suite and establish new infrastructure, leading IBM X-Force IRIS to assess with medium confidence that OceanLotus will be an ongoing threat to organizations involved in Southeast Asia.",
            "entitlement": "premium",
            "indicators": [],
            "primary_tag": "thr.hive0013",
            "tags": [
                "thr.hive0013",
                "bhv.meth.coopt.masq.prod.media.qq",
                "bhv.role.installer",
                "bhv.meth.codelang.powershell",
                "bhv.capa.file.read",
                "bhv.role.downloader",
                "bhv.capa.dir.list",
                "bhv.capa.encode.base64",
                "bhv.capa.datamine.documents",
                "bhv.meth.netops.hardcoded.useragent",
                "bhv.capa.datamine.clipboard",
                "bhv.meth.coopt.masq.org.adobe",
                "bhv.capa.persist.svc",
                "bhv.capa.drive.list",
                "bhv.aka.vt.tag.run_dll",
                "bhv.capa.comm.http",
                "bhv.aka.vt.tag.cve_2018_0802",
                "bhv.published.cylance",
                "bhv.aka.vt.tag.cve_2012_0158",
                "bhv.aka.pt.tag.malicious",
                "bhv.aka.cylance.mal.cobaltstrike",
                "bhv.aka.vt.tag.exe_pattern",
                "bhv.capa.schtask.create",
                "bhv.capa.ps.create",
                "bhv.capa.regkey.create",
                "bhv.aka.vt.tag.doc",
                "bhv.aka.vt.tag.create_ole",
                "bhv.published.fireeye",
                "bhv.aka.vt.tag.url_pattern",
                "bhv.aka.vt.tag.cve_2017_11882",
                "mal.gen",
                "bhv.capa.regkey.read",
                "bhv.meth.coopt.decoy.syserror",
                "bhv.aka.nccgroup.mal.cobaltstrike",
                "bhv.capa.crypt",
                "bhv.aka.eset.thr.oceanlotus",
                "bhv.capa.persist.schtasks",
                "bhv.meth.fileops.macro",
                "bhv.aka.vt.tag.copy_file",
                "bhv.meth.persist.svc",
                "bhv.aka.vt.tag.obfuscated",
                "bhv.aka.vt.tag.64bits",
                "bhv.aka.vt.tag.powershell",
                "bhv.aka.vt.tag.hide_app",
                "bhv.aka.pt.tag.suspicious",
                "bhv.role.loader",
                "bhv.aka.vt.tag.rtf",
                "bhv.aka.vt.tag.pedll",
                "bhv.capa.file.download",
                "bhv.capa.c2.dns",
                "bhv.role.backdoor",
                "bhv.capa.c2.web",
                "bhv.capa.file.del.self",
                "bhv.aka.vt.tag.macho",
                "bhv.aka.fireeye.thr.oceanlotus",
                "bhv.meth.coopt.masq.prod.media.flash",
                "bhv.aka.vt.tag.multi_arch",
                "bhv.aka.vt.tag.macros",
                "bhv.use.hive0013",
                "bhv.capa.perist.regkey",
                "bhv.aka.qihoo360.thr.oceanlotus",
                "bhv.meth.persist.schtask",
                "bhv.capa.sleep",
                "bhv.capa.dir.create",
                "bhv.capa.ps.kill",
                "bhv.aka.vt.tag.create_file",
                "bhv.aka.vt.tag.text",
                "bhv.aka.cylance.mal.denis",
                "bhv.aka.vt.tag.peexe",
                "bhv.meth.fileops.obf.encrypt",
                "bhv.capa.ps.inject",
                "bhv.capa.regkey.mod",
                "bhv.aka.vt.tag.cve_2017_0199",
                "bhv.capa.anti.vm",
                "bhv.role.dropper",
                "bhv.aka.vt.tag.dos_stub",
                "bhv.capa.anti.sideload",
                "bhv.aka.vt.tag.enum_windows",
                "bhv.published.telsy",
                "bhv.published.eset",
                "bhv.aka.vt.tag.overlay",
                "bhv.aka.fireeye.thr.apt32",
                "bhv.capa.exec.cmd",
                "bhv.aka.vt.tag.run_file",
                "thr",
                "bhv.aka.vt.tag.ole_embedded",
                "bhv.meth.webcomp.payload",
                "bhv.aka.vt.tag.environ",
                "bhv.meth.coopt.masq.prod.bus.office",
                "bhv.aka.vt.tag.exploit",
                "bhv.capa.file.mov",
                "bhv.capa.svc.create",
                "bhv.aka.telsy.thr.oceanlotus",
                "bhv.capa.ps.list",
                "bhv.meth.netops.ssl.cert.signed.self",
                "bhv.capa.file.del",
                "bhv.capa.datamine.keylog",
                "bhv.meth.persist.regkey",
                "bhv.meth.fileops.obf.encode.base64",
                "bhv.aka.cylance.thr.oceanlotus",
                "bhv.meth.coopt.masq.org.cisco",
                "bhv.aka.vt.tag.write_file",
                "bhv.capa.persist.regkey",
                "bhv.capa.file.create",
                "bhv.published.qihoo360",
                "bhv.published.nccgroup",
                "bhv.aka.pt.tag.ddns",
                "bhv.aka.vt.tag.registry",
                "bhv.meth.c2",
                "bhv.aka.vt.tag.docx",
                "bhv.capa"
            ],
            "content": "# Hive0013 Analysis Report\n\n## Summary\nSince at least 2014, likely Vietnam-sponsored Advanced Persistent Threat (APT)"
        }
